project_type: node
slug: travelwithshego
port: 3000

domains:
  prod: travelwithshego.com
  admin: admin.travelwithshego.com

deploy_targets:
  main-hetz: hetzner
  dev: vercel
  preview: vercel

pgadmin_subdomain: dbui
pgadmin_subdomain: db
